apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: expense-ingress
  namespace: expense-ai
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: expense.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: expense-frontend-svc
                port:
                  number: 80
