apiVersion: v1
kind: Service
metadata:
  name: expense-frontend-svc
  namespace: expense-ai
spec:
  type: ClusterIP
  selector:
    app: expense-frontend
  ports:
    - port: 80
      targetPort: 3000
