apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: expense-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host: 98.90.127.76.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: expense-service
                port:
                  number: 3000

