apiVersion: v1
kind: Secret
metadata:
  name: expense-secret
type: Opaque
stringData:
  DATABASE_URL: "REPLACE"
  CLERK_SECRET_KEY: "REPLACE"
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: "REPLACE"
  NEXT_PUBLIC_APP_URL: "REPLACE"
  GROQ_API_KEY: "REPLACE"
  GEMINI_API_KEY: "REPLACE"
  NEXT_PUBLIC_GEMINI_API_KEY: "REPLACE"
